export const projects = [
  {
    id: 'ibengcam',
    title: 'Ibengcam Repair',
    category: 'Local Service · Website',
    tag: 'Client Work',
    tagColor: 'green',
    description:
      'Professional camera & production equipment repair service in Indonesia. Built to convert visitors through trust, speed, and direct WhatsApp lead routing.',
    url: 'https://ibengcam.vercel.app',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/05fef6fe1_69cfa419d67de003ba16a149.jpg',
    accentColor: '#f97316',
    device: 'browser',
    screenshots: [
      'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/c764a3cb7_screencapture-ibengcam-id-2026-04-03-18_28_38.png',
    ],
    metrics: [
      { label: 'Load Time', value: '<1s' },
      { label: 'WhatsApp CTA', value: '1-click' },
      { label: 'Mobile Score', value: '98/100' },
    ],
    tech: ['React', 'Vercel', 'WhatsApp API'],
  },
  {
    id: 'esbc',
    title: 'Eastside Boxing Camp',
    category: 'Sports & Fitness · Website',
    tag: 'Client Work',
    tagColor: 'green',
    description:
      'High-energy boxing camp website with a premium athletic identity. Built to drive class signups and establish the brand as a serious training destination.',
    url: 'https://esbc.vercel.app',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/ce1f69816_Screenshot2026-04-04011007.png',
    accentColor: '#ef4444',
    device: 'browser',
    screenshots: [
      'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/7de66baef_screencapture-esbc-vercel-app-2026-04-03-18_31_10.png',
    ],
    metrics: [
      { label: 'Class Signups', value: '+40%' },
      { label: 'Brand Score', value: 'A+' },
      { label: 'Mobile UX', value: '100' },
    ],
    tech: ['React', 'Vite', 'Tailwind CSS'],
  },
  {
    id: 'aura-saas',
    title: 'Aura — Business Intelligence',
    category: 'SaaS · Web App',
    tag: 'Template',
    tagColor: 'purple',
    description:
      'Enterprise-grade AI-powered business performance dashboard. Real-time revenue analytics, agent confidence scoring, and automated growth actions.',
    url: 'https://aura-saas.base44.app/',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/be4c25a19_image.png',
    accentColor: '#a3e635',
    device: 'browser',
    metrics: [
      { label: 'Data Points', value: '500+' },
      { label: 'AI Confidence', value: '84%' },
      { label: 'Render Time', value: '0.3s' },
    ],
    tech: ['React', 'Recharts', 'AI Agent', 'Base44'],
  },
  {
    id: 'wiserun',
    title: 'WiseRun — Fitness Tracker',
    category: 'Health & Fitness · Native App',
    tag: 'Template',
    tagColor: 'purple',
    description:
      'Next-generation personal fitness tracker with AI biometric analysis, Strava sync, sleep scoring, and real-time VO₂ max monitoring. Light & dark modes.',
    url: 'https://wise-run-4cd47429.base44.app/',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/2bec4f1bb_image.png',
    accentColor: '#eab308',
    device: 'browser',
    metrics: [
      { label: 'AI Features', value: '8+' },
      { label: 'Data Views', value: 'Dark/Light' },
      { label: 'Strava Sync', value: 'Live' },
    ],
    tech: ['React', 'AI Assistant', 'Recharts', 'Base44'],
  },
  {
    id: 'ai-receptionist',
    title: 'Evelina — AI Receptionist',
    category: 'AI Automation · SaaS',
    tag: 'Template',
    tagColor: 'purple',
    description:
      'Voice-enabled AI receptionist that books appointments, answers FAQs, and handles client calls 24/7. Built for salons, spas, and service businesses.',
    url: 'https://abstract-sphere-dashboard-cf634de0.base44.app/',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/ba20cf5dd_image.png',
    accentColor: '#84cc16',
    device: 'browser',
    metrics: [
      { label: 'Booking Rate', value: '83%' },
      { label: 'Calls/day', value: '24/7' },
      { label: 'Setup Time', value: '<1hr' },
    ],
    tech: ['Voice AI', 'Automation', 'SMS', 'Base44'],
  },
  {
    id: 'o2-apparel',
    title: 'O2® — Luxury Apparel Store',
    category: 'E-Commerce · Web App',
    tag: 'Template',
    tagColor: 'purple',
    description:
      'Ultra-premium glass-morphism fashion storefront with cosmic visual identity. Chaos & Cozy dual mode, immersive product presentation, and frictionless checkout.',
    url: 'https://o2-apparel-968b77b1.base44.app/',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/caf1c05e5_image.png',
    accentColor: '#94a3b8',
    device: 'browser',
    metrics: [
      { label: 'Visual Style', value: 'Glassmorphism' },
      { label: 'Modes', value: 'Chaos/Cozy' },
      { label: 'Conversion', value: 'Optimized' },
    ],
    tech: ['React', 'Three.js', 'Glass UI', 'Base44'],
  },
  {
    id: 'nexus-os',
    title: 'Nexus OS — AI Platform',
    category: 'AI Infrastructure · SaaS',
    tag: 'Template',
    tagColor: 'purple',
    description:
      'Deploy and scale AI agents with neural nodes. Enterprise-grade AI infrastructure with <10ms latency, 10M+ request handling, and real-time developer SDK.',
    url: 'https://nexus-os-df5b2828.base44.app/',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/f796c59a7_image.png',
    accentColor: '#22d3ee',
    device: 'browser',
    metrics: [
      { label: 'Latency', value: '<10ms' },
      { label: 'Scale', value: '10M+ req' },
      { label: 'Models', value: '99.9% uptime' },
    ],
    tech: ['AI Agents', 'Neural Nodes', 'SDK', 'Base44'],
  },
  {
    id: 'personal-site',
    title: 'Premium Personal Website',
    category: 'Personal Brand · Portfolio',
    tag: 'Template',
    tagColor: 'purple',
    description:
      'Typographic-first personal portfolio for operators, founders, and builders. Ultra-minimal with maximum impact — building at the intersection of business, product & taste.',
    url: 'https://premiumpersonalwebsite.base44.app/',
    screenshotUrl: 'https://media.base44.com/images/public/69cc2ed917e94df8870cff9d/cb2a19704_image.png',
    accentColor: '#f1f5f9',
    device: 'browser',
    metrics: [
      { label: 'Style', value: 'Editorial' },
      { label: 'Load Time', value: 'Instant' },
      { label: 'Impression', value: 'Elite' },
    ],
    tech: ['React', 'Framer Motion', 'Typography', 'Base44'],
  },
];